version: '3.8'

services:
  frontend:  # Custom name for the web service
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/.env:/app/.env
    environment:
      - NAME=World
    depends_on:
      - backend

  backend:  # Custom name for the web service-
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports: 
      - "5080:5080"
    volumes:
      - ./backend/.env:/app/.env
    environment:
      - NAME=World
    depends_on:
      - db

  update_service:  # Custom name for the web service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: update_app
    ports:
      - "4000:4000"
    volumes:
      - ./src:/workspace/src 
      - ./include:/workspace/include
      - ./docker-compose.yml:/workspace/docker-compose.yml
      - ./lib:/workspace/lib
      - ./Dockerfile:/workspace/Dockerfile
      - ./makefile:/workspace/makefile
      - ./README.md:/workspace/README.md
      - ./.env:/workspace/.env
      - ./.git:/workspace/.git
      - ~/.ssh:/root/.ssh ###IMPORTANT UPDATE SSH KEYS SOMETIMES
      - ./.gitignore:/workspace/.gitignore
    environment:
      - NAME=World
    command: /bin/bash -c "cd /workspace && make && /workspace/bin/app"
    
    # tail -f /dev/null

  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
